const mongoose = require("mongoose");

const criteriaSchema = new mongoose.Schema({
  role: {
    type: String,
    enum: ["user", "admin", "vendor"]
  },

  isVendor: Boolean,
  isUser: Boolean,

  // User filters
  phoneVerified: Boolean,

  // Vendor filters
  category: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Category"
  },

  serviceLocation: String,
  pincode: String,

  selectedPriceTier: {
    type: String,
    enum: ["basic", "premium", "premiumPlus"]
  },

  // Common filters
  createdAfter: Date,
  createdBefore: Date

}, { _id: false });

const topicSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      unique: true,
      trim: true
    }, // e.g., 'all_users', 'premium_users', 'delhi_users', 'offers'
    
    topicName: {
      type: String,
      unique: true,
      trim: true
    }, // Firebase topic name in format: 'group_all_users', 'group_premium_users' (generated by pre-save)
    
    displayName: {
      type: String,
      required: true
    }, // e.g., 'All Users', 'Premium Users', 'Delhi Users'
    
    description: {
      type: String
    }, // Description of what this topic is for

    isActive: {
      type: Boolean,
      default: true
    },
    
    subscriberCount: {
      type: Number,
      default: 0
    }, // Track how many devices are subscribed
    
    autoSubscribe: {
      type: Boolean,
      default: false
    }, // Auto-subscribe new devices to this topic (e.g., 'all_users')
    
    criteria: {
      type: criteriaSchema,
      default: null
    } // Optional: Auto-subscription criteria (e.g., {userType: 'premium'})
  },
  { timestamps: true }
);

// Pre-save middleware to auto-generate topicName from name
topicSchema.pre('save', function(next) {
  if (this.isNew || this.isModified('name')) {
    // Standardize: convert name to lowercase, replace spaces with underscores
    const formattedName = this.name.toLowerCase().trim().replace(/[^a-z0-9_]/g, '_');
    this.topicName = `group_${formattedName}`;
  }
  next();
});

module.exports = mongoose.model("Topic", topicSchema);
